config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :user_questionnaires
  resources :user_answers

  resources :questionnaires do
    resources :questions do
      resources :answers
    end
  end

  root 'questionnaires#index'
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  belongs_to :questionnaire
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_questionnaire
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = @questionnaire.questions.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = @questionnaire.questions.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = @questionnaire.questions.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to questionnaire_question_path(@questionnaire, @question), notice: 'Question was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to questionnaire_question_path(@questionnaire, @question), notice: 'Question was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questionnaire_questions_path(@questionnaire, @question), notice: 'Question was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:questionnaire_id])
    end

    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:name, :questionnaire_id, :question_type)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for([@questionnaire, @question]) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :question_type %><br>
    <%= f.select(:question_type, options_for_select([ ['open', 'open'], ['choice', 'choice'], ['multiple', 'multiple'], ['rating', 'rating'] ])) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Edit Answers', questionnaire_question_answers_path(@questionnaire, @question), class: 'btn btn-default' %>
<%= link_to 'Back', questionnaire_questions_path(@questionnaire), class: 'btn btn-default' %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Questionnaire</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.name %></td>
        <td><%= question.questionnaire.name %></td>
        <td><%= question.question_type %></td>
        <td><%= link_to 'Edit', edit_questionnaire_question_path(@questionnaire, question), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', questionnaire_question_path(@questionnaire, question), method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_questionnaire_question_path(@questionnaire), class: 'btn btn-success' %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questionnaire_questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @question.name %>
</p>

<p>
  <strong>Questionnaire:</strong>
  <%= @question.questionnaire.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @question.question_type %>
</p>


<table class='table table-hover'>
  <thead>
    <tr>
      <th>Answers</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question.answers.each do |answer| %>
      <tr>
        <td><%= answer.question.name %></td>
        <td><%= answer.value %></td>
        <td><%= link_to 'Show', questionnaire_question_answer_path(@questionnaire, @question, answer) %></td>
        <td><%= link_to 'Edit', edit_questionnaire_question_answer_path(@questionnaire, @question, answer) %></td>
        <td><%= link_to 'Destroy', questionnaire_question_answer_path(@questionnaire, @question, answer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Add Answer', new_questionnaire_question_answer_path(@questionnaire, @question), class: 'btn btn-success' %>
<%= link_to 'Edit', edit_questionnaire_question_path(@questionnaire, @question), class: 'btn btn-warning' %>
<%= link_to 'Back', questionnaire_questions_path, class: 'btn btn-default' %>