config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :user_questionnaires
  resources :user_answers

  resources :questionnaires do
    resources :questions do
      resources :answers
    end
  end

  root 'questionnaires#index'
end

app/models/user_answer.rb
class UserAnswer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  belongs_to :answer
end

app/helpers/user_answers_helper.rb
module UserAnswersHelper
end

app/views/user_answers/_form.html.erb
<%= form_for(@user_answer) do |f| %>
  <% if @user_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_answer.errors.count, "error") %> prohibited this user_answer from being saved:</h2>

      <ul>
      <% @user_answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.text_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :answer_id %><br>
    <%= f.text_field :answer_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_area :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_answers/edit.html.erb
<h1>Editing user_answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_answer %> |
<%= link_to 'Back', user_answers_path %>

app/views/user_answers/index.html.erb
<h1>Listing user_answers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Question</th>
      <th>Answer</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_answers.each do |user_answer| %>
      <tr>
        <td><%= user_answer.user %></td>
        <td><%= user_answer.question %></td>
        <td><%= user_answer.answer %></td>
        <td><%= user_answer.value %></td>
        <td><%= link_to 'Show', user_answer %></td>
        <td><%= link_to 'Edit', edit_user_answer_path(user_answer) %></td>
        <td><%= link_to 'Destroy', user_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User answer', new_user_answer_path %>

app/views/user_answers/new.html.erb
<h1>New user_answer</h1>

<%= render 'form' %>

<%= link_to 'Back', user_answers_path %>

app/views/user_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_answer.user %>
</p>

<p>
  <strong>Question:</strong>
  <%= @user_answer.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @user_answer.answer %>
</p>

<p>
  <strong>Value:</strong>
  <%= @user_answer.value %>
</p>

<%= link_to 'Edit', edit_user_answer_path(@user_answer) %> |
<%= link_to 'Back', user_answers_path %>