config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :user_questionnaires
  resources :user_answers

  resources :questionnaires do
    resources :questions do
      resources :answers
    end
  end

  root 'questionnaires#index'
end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  has_many :questions
  def full?
    self.questions.count >= self.max_questions
  end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy]
  before_action :check_admin!

  # GET /questionnaires
  # GET /questionnaires.json
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1
  # GET /questionnaires/1.json
  def show
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires
  # POST /questionnaires.json
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /questionnaires/1
  # PATCH/PUT /questionnaires/1.json
  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /questionnaires/1
  # DELETE /questionnaires/1.json
  def destroy
    @questionnaire.destroy
    respond_to do |format|
      format.html { redirect_to questionnaires_url, notice: 'Questionnaire was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionnaire_params
      params.require(:questionnaire).permit(:name, :desc)
    end
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/questionnaires/_form.html.erb
<%= form_for(@questionnaire) do |f| %>
  <% if @questionnaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questionnaire.errors.count, "error") %> prohibited this questionnaire from being saved:</h2>

      <ul>
      <% @questionnaire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :desc %><br>
    <%= f.text_area :desc, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questionnaires/edit.html.erb
<h1>Editing questionnaire</h1>

<%= render 'form' %>

<%= link_to 'Show', @questionnaire %> |
<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/index.html.erb
<% if current_user %>
<h1>Listing questionnaires</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionnaires.each do |questionnaire| %>
      <tr>
        <td><%= link_to questionnaire.name, questionnaire_path(questionnaire) %></td>
        <td><%= questionnaire.desc %></td>
        <td><%= link_to 'Show', questionnaire %></td>
        <td><%= link_to 'Edit', edit_questionnaire_path(questionnaire) %></td>
        <td><%= link_to 'Destroy', questionnaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questionnaire', new_questionnaire_path, class: 'btn btn-success' %>
<% end %>

app/views/questionnaires/new.html.erb
<h1>New questionnaire</h1>

<%= render 'form' %>

<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Name:</strong>
<%= @questionnaire.name %>
</p>

<p>
<strong>Desc:</strong>
<%= @questionnaire.desc %>
</p>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @questionnaire.questions.each do |question| %>
    <tr>
    <td><%= link_to question.name, questionnaire_question_path(@questionnaire, question) %></td>
    <td><%= question.question_type %></td>
    <td><%= link_to 'Edit', edit_questionnaire_question_path(@questionnaire, question) %></td>
    <td><%= link_to 'Edit Answers', questionnaire_question_answers_path(@questionnaire, question) %></td>
    <td><%= link_to 'Destroy', questionnaire_question_path(@questionnaire, question), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
  </tbody>
</table>

<%= link_to 'New question', new_questionnaire_question_path(@questionnaire), class: 'btn btn-success' %>
<%= link_to 'Edit', edit_questionnaire_path(@questionnaire), class: 'btn btn-warning' %>
<%= link_to 'Back', questionnaires_path, class: 'btn btn-default' %>